project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - posts.qmd
      - href: ./posts/DeepLearningCommunityofPractice/index.qmd
        text: Deep Learning Community

format:
  html:
    theme: simplex
    css: styles.css
    toc: true

editor: source

